[build]
  publish = "_site"
  command = "bundle exec jekyll build"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.2"

[context.production.environment]
  JEKYLL_ENV = "production"

[context.deploy-preview]
  command = "bundle exec jekyll build"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
